; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.1 on Thu Jun 04 2020 06:16:21 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


