; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.1 on Thu Jun 04 2020 06:16:23 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

