; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.1.1 on Thu Jun 04 2020 06:16:22 GMT-0400 (Eastern Daylight Time)
G91               ; relative positioning
G1 H1 Y500 F1800  ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y-5 F6000   ; go back a few mm
G1 H1 Y20 F360    ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning

