; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.1 on Thu Jun 04 2020 06:16:22 GMT-0400 (Eastern Daylight Time)
M83            ; relative extruder moves
G1 E-3 F1800   ; retract 3mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0

