; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.1 on Thu Jun 04 2020 06:16:22 GMT-0400 (Eastern Daylight Time)

